{
 "title": "Subtivity",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(transaction_traces{job=\"subtivity-antelope\"}[10m]) / 600",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(transaction_traces{job=\"subtivity-eth\"}[10m]) / 600",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(transaction_traces{job=\"subtivity-wax\"}[10m]) / 600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "delta(transaction_traces{job=\"subtivity-antelope\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(transaction_traces{job=\"subtivity-eth\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(transaction_traces{job=\"subtivity-wax\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trace Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "delta(trace_calls{job=\"subtivity-antelope\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(trace_calls{job=\"subtivity-eth\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(trace_calls{job=\"subtivity-wax\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "head_block_drift{job=\"subtivity-antelope\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "head_block_drift{job=\"subtivity-eth\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "head_block_drift{job=\"subtivity-wax\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_block_number{job=\"subtivity-antelope\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_block_number{job=\"subtivity-eth\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_block_number{job=\"subtivity-wax\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Timestamp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_block_timestamp{job=\"subtivity-antelope\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_block_timestamp{job=\"subtivity-eth\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_block_timestamp{job=\"subtivity-wax\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}