[package]
name = "subtivity_stores"
version = "0.1.0"
description = "Subtivity Stores."
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = { workspace = true }
subtivity-common = { path = "../common" }
