[package]
name = "subtivity_store_antelope"
version = "0.1.0"
description = "Subtivity for Antelope Store"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams-antelope = { workspace = true }
substreams = { workspace = true }
subtivity-common = { path = "../../common" }
